### ISSUE TITLE
Buy weapon

### ISSUE THREAD

**Issue by duncosta** [Jaboticnik/Mafiavolta#2]
Hi , what line need to modify in client.lua to activate "buy weapon" only for "boss" ?

**Comment by Jaboticnik** [comment]
They cant buy weapons from nowhere, they have to buy weapons from weaponshop or blackmarket. In their house, they only have storage for weapons, not a shop or something similar.

**Comment by duncosta** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/75456318/147494616-e35535ee-dd22-438f-947f-9594eb71bc08.png)

Hi, from this menu I wanted to buy weapons. I solved the problem. Thank you
